### ISSUE TITLE
Auto Generate anonymousId if userId or anonymousId not explicitly set

### ISSUE THREAD

**Issue by perryao** [segmentio/analytics-node#163]
In my opinion, requiring either userId or anonymousId for every track, page, etc call is a bit too strict. There are cases where I want to track an event that might not be explicitly tied to a user. So of course I can do that myself, but it would be cleaner if analytics-node could do that for me. Thinking something like
https://github.com/dylang/shortid could be used.

**Comment by perryao** [comment]
Also, since analytics.js already does this, this seems like a feature worth having for parity. 

See: https://segment.com/docs/sources/website/analytics.js/#anonymous-id

**Comment by f2prateek** [comment]
Analytics.js is meant for use in a single user/client side context. It can also store the id in local storage so that the ID doesn't change between different sessions. 

This library is meant to be used in a server side context and typically is associated with multiple users. It also doesn't have a reliable way to persist generate ideas to disk (since it depends on how your node app is running).

Lastly I would rather not generate the ids randomly ourselves since we bill folks based on the number of monthly users - using a random id on each "session" would inflate your MTU count and incur higer billing charges.

In general, every Segment action should be tied to a user. If it's not tied to a user - we typically use a username for system making the request (e.g. we use `segment-bot`).
