### ISSUE TITLE
How to determine bad write key?

### ISSUE THREAD

**Issue by anishkny** [segmentio/analytics-node#235]
Following up on 2016 issue #59. 

Is there a way to determine if the client has a bad write key? Thanks! 🙏 @ivolo @travisjeffery @f2prateek

**Comment by pbassut** [comment]
Hello!
The response in #59 looks ok to me. 

Can you go over your particular use case so we can try to figure out another solution?

**Comment by anishkny** [comment]
I have since moved on to a new team. IIRC back then we wanted to fail early if the server using `analytics-node` was provided a bad write key. Basically the following should throw so that appropriate action can be taken:

```
const client = new Analytics('bad-write-key');  // BOOM! Should throw error!
```

**Comment by pbassut** [comment]
Hm, gotcha. Unfortunately there's no way to do that as of now. But I'll update this issue if I find something.
Thanks for clarifying!

**Comment by tniemann** [comment]
any progress here?

**Comment by pbassut** [comment]
Not sure what is possible here. It depends on the level of granularity that we want to determine a bad write key. Every write key is 32 characters long. We can check if it has that length and if it does, we still can't determine it's valid. We can infer something only if it doesn't.

And given the answer in #59 analytics services almost never return something not-200. So we can't just call an endpoint asking if a write key is valid. 

One approach, could be setting up a webhook as a destination for your source, and if it the data you send using the write key hits that webhook then you know it's valid. Otherwise, you flag the write key as invalid in your system.

**Comment by anishkny** [comment]
First the API needs to expose a method to determine write key validity, which can then be added to this library. Since we are not aware of a public forum to suggest enhancements to the API, can we use this issue as a stand-in for both?

**Comment by pbassut** [comment]
This is the proper channel to suggest things to underlying API. I'll take it to the team and they will evaluate. 

Again, wouldn't the webhook approach work for the time being?

**Comment by anishkny** [comment]
> Again, wouldn't the webhook approach work for the time being?

To be perfectly honest, it seems kind of roundabout and prone to seemingly avoidable errors. I would personally rather wait to see the proper support in a more straightforward manner in the API itself. Just my $.02

**Comment by nd4p90x** [comment]
@anishkny Thank you for your inquiry, after discussing this with the team, this request is not a core feature for any of segments libraries.  We understand your frustrations, however, managing write keys is the responsibility of the consumer as well as verifying the accuracy of those write keys. Please let us know if we can assist with any future requests. @pbassut
