### ISSUE TITLE
Bad Request (400) when batching

### ISSUE THREAD

**Issue by yonatandbinahai** [segmentio/analytics-node#313]
Using analytics-node v 3.5.0 with Segment.
When using the following configuration:
```
{
   flushAt: 1000,
   flushAfter: 15000
}
```

I get intermittent 400 - Bad Request responses from Segment without any clear error message.
However I noticed that the request's content length is 535982 bytes, which is over the 500KB limit.

Any idea?

**Comment by felipe-najson-ntf** [comment]
Hi @yonatandbinahai, sorry for the late reply. 
I just tested a couple of cases with your configuration..
```
{
   flushAt: 1000,
   flushAfter: 15000
}
```
doing simple track requests and everything is working fine.
Maybe you could give me more information or upload a snippet code about what you are executing specifically in order to reproduce the error.

Thanks, Segment team.
