### ISSUE TITLE
`Analytics` intialization doesn't catch invalid/non-existent write key

### ISSUE THREAD

**Issue by chasebish** [segmentio/analytics-node#371]
With the following code:
```typescript
const segmentAnalytics = new Analytics("unusable_write_key");
```
no error is thrown by the constructor.

When using `analytics-next`, this error is sufficiently caught, as seen here:
```typescript
const segmentAnalytics = new AnalyticsBrowser();
segmentAnalytics
  .load({
    "unusable_write_key",
  })
  .catch(() => {
    doSomething();
  });
```

Is there plan to add support to the `analytics-node` client that will enable catching a bad write key?

**Comment by nd4p90x** [comment]
@chasebish Thank you for realizing this issue with analytics-node, unfortunately this package has been deprecated and it is recommended that everyone begin to use the analytics-next/node package:

https://github.com/segmentio/analytics-node#-this-package-is-deprecated

https://github.com/segmentio/analytics-next/tree/master/packages/node#readme

Sorry for any inconvenience this may cause you and your team.

Thank you for your patronage.

**Comment by silesky** [comment]
Just a heads up, this isn't possible in any of our node libraries (AFAIK, none of our server side libs at all). We do not validate writeKeys beyond their existence / type on instantiation or on our generic ingestion APIs do not support it for perf reasons; and it would require a separate API calls.

It only works on the browser because we need to use the WriteKey to fetch settings which enables analytics to begin with. The server never fetches settings.
