### ISSUE TITLE
How to handle errors when messages are automatically flushed?

### ISSUE THREAD

**Issue by conorgil** [segmentio/analytics-node#67]
In version 0.6.0, analytics-node was also an EventEmitter and we could register callbacks for `error` and `flush` events. We used that to log any errors which occurred and also when the library flushed messages (for debugging). Obviously, the library is very different now that it is on v2.x, but what is the recommended method for error handling now? Do I have to register a callback with each and every call to a method which calls `enqueue()` internally (`identify()`, etc)?

**Comment by thesmart** [comment]
I have the same question.  CMIIW, @dominicbarnes, but the error handling seems logically unsound.  Calling `track` n-times, there's no way to determine which subset of `track` calls failed when the batch fails because all the track callbacks are called with the single batch call error.  The [batch method documentation](https://segment.com/docs/sources/server/http/#batch) contains no information about the response...  does it fail all if one fails? Are payloads partially accepted?

I suppose we need to error-handle every individual call, and we won't know which specific calls failed.  I suppose turning off automatic batching would help error handling but sacrifice performance.

**Comment by vadimdemedes** [comment]
I agree with @thesmart, the error handling of tracking methods (`identify()`, `track()`, etc) doesn't make much sense to me. While we could easily add `flush` event, I'm not sure what purpose would it serve. I'd expect analytics library to handle tracking/sending errors by itself. E.g. if `flush()` fails, I'd expect it to reschedule the flush and retry. But I wouldn't want to handle that logic manually.

@conorgil could you share more about your use case and what do you want to achieve with `error` and `flush` events? It would make it easier to understand the benefit of having those events.

**Comment by vadimdemedes** [comment]
Closing due to lack of response. If issue isn't resolved, feel free to reply and I'll reopen it.
