### ISSUE TITLE
`flush()` callback not reliable if there's a pending flush, can lead to out-of-order events

### ISSUE THREAD

**Issue by bradvogel** [segmentio/analytics-node#95]
Consider the following code:

```
var Analytics = require('analytics-node');
var analytics = new Analytics('<write key>', {
  flushAt: 1
});

analytics.identify({
  userId: '019mr8mf4r',
  traits: {
    name: 'Michael Bolton',
    email: 'mbolton@initech.com',
    plan: 'Enterprise',
    friends: 42
  }
}, function() {
  console.log('done with identify');
});

analytics.flush(function() {
  console.log('done flushing')
});
```

I would expect `done flushing` to be logged _after_ `done with identify`, but it is not. Intuitively I'd expect `flush()` to only call its callback once _all_ pending calls have been flushed.

**Why is this an issue?**

Because we need to be certain that the `identify()` call completes _before_ calling `track()`. Otherwise the `track()` won't carry the trait information sent in `identify()`.

So, for instance, the following code:

```
var Analytics = require('analytics-node');
var analytics = new Analytics('<write key>', {
  flushAt: 1
});

analytics.identify({
  userId: '019mr8mf4r',
  traits: {
    name: 'Michael Bolton',
    email: 'mbolton@initech.com',
    plan: 'Enterprise',
    friends: 42
  }
}, function() {
  console.log('done with identify');
});

analytics.flush(function() {
  analytics.track({
    userId: '019mr8mf4r',
    event: 'first event after identify'
  }, function() {
    console.log('done with first event')
  });
});
```

will log:
```
sending event that I want to go after identify()
done with first event
done with identify
```

This is wrong because the `track()` call is completing _before_ the `identify()` completes, despite the code flushing in between the calls.

I understand that the fix is to call `track()` in the callback of `identify()`, and the call `flush()` after without a callback. But this isn't intuitive at all to the user.

**Comment by vadimdemedes** [comment]
Since you set `flushAt` to `1`, there's no need to call `flush()` manually, it will be called for you after each `identify()`, `track()` and other tracking methods.

As you correctly pointed out, in this specific case, calling `track()` in the callback of `identify()` would fix this.

> Because we need to be certain that the `identify()` call completes _before_ calling `track()`. Otherwise the `track()` won't carry the trait information sent in `identify()`.

I think the solution for this problem doesn't lie in the `flush()` logic itself, but in `identify()`. `analytics-node` should automatically flush after `identify()` is executed, so that all the following calls carry the correct trait information. Since `identify()` isn't called often, I don't think it's going to "over-flush". 

cc @stevenmiller888

**Comment by vadimdemedes** [comment]
@bradvogel Could you modify your code according to the above post and see if you are still missing the traits in the following `track()` calls?

**Comment by f2prateek** [comment]
hey @bradvogel let us know if you still have this issue. Closing for now.
